# Sync on startup/reload
StartUpSync: true

# Shared location relative to server jar, where the objects are stored
SharedLocation: "../Share"

# Collection of files/folders to synchronize
Synchronizations:
  # Name of the shared object
  Help:
    # Locations to synchronize relative to server jar, must be inside the server folder!
    Locations:
      - "help.yml"
    # Command to execute when changes are processed
    Command: "say synchronized"
    # Mode of the synchronization of the object (push, pull, manual, none)
    Mode: manual
    # Maximal number of versions to keep (none positive values -> keep all)
    Versions: 5
